better error
observablehq/plot pull request #1282
Opened 2023-02-17 09:55 UTC by Fil

closes #1281

2023-02-17 16:54 UTC, mbostock requested changes

2023-02-17 16:54 UTC, mbostock commented on src/plot.js
> +        if (facetState === undefined) throw new Error(`the facet: "exclude" option is restricted to top-level facets`);
This isn’t accurate—you can also use `facet: "exclude"` if you specify mark-level faceting, e.g.

```js
Plot.dot(penguins, {facet: "exclude", fx: "sex", fy: "species", x: "culmen_depth_mm", y: "culmen_length_mm", r: 2, fill: "#ddd"}),
```

2023-02-21 13:04 UTC, Fil commented
We should be consistent when the **facet** option is activated (ie not undefined) on a non-faceted mark: either ignore all cases, or error all cases.

Currently we ignore all cases but crash on "exclude". This can be fixed by changing that line to:
>         if (facetState !== undefined) facetState.facetsIndex = facetExclude(facetState.facetsIndex);

I'm not sure erroring on all cases would bring much, but it's an alternative.

2023-02-21 13:06 UTC, Fil commented on src/plot.js
>          facetState.facetsIndex = facetExclude(facetState.facetsIndex);
```suggestion
        if (facetState !== undefined) facetState.facetsIndex = facetExclude(facetState.facetsIndex);
```

2023-02-21 16:39 UTC, mbostock approved these changes

2023-02-21 16:41 UTC, merged