document group
observablehq/plot pull request #1360
Opened 2023-03-20 10:56 UTC by Fil

for #1343 

Note: this is already very long, and doesn't yet include comments on using the sort{ fy: "x", limit: 10} input option.

2023-03-20 14:57 UTC, Fil commented
I've just added an incomplete commit that shows an underlying type bug with ChannelReducers. Not sure how to solve this.

2023-03-20 17:52 UTC, mbostock commented
> The incomplete test is in test/plots/penguin-island-mode.ts; it fails because our types aren't certain that the reduce function is called with two arguments

That’s only true in this branch because you changed the definition of ReducerImplementation. In the main branch TypeScript seems to infer that it’s a ReducerImplementation:

<img width="604" alt="Screenshot 2023-03-20 at 10 44 31 AM" src="https://user-images.githubusercontent.com/230541/226423650-6edb5aca-443c-42e1-8113-b3a7d2098bdb.png">

But, I do think there is ambiguity and likely a bug here introduced by #1310 (to fix #1309). Take this code:

```js
Plot.groupX({y: "count", fill: {reduce: f}}, {x: "species", fill: "island"})
```

In this case, it’s hard to tell whether the **fill** output channel is being specified as

1. a reducer with a scale override, in which case *f* is a ReducerFunction (or a ReducerImplementation object)
2. a reducer implementation, in which case *f* is a ReducerImplementation["reduce"]

Currently we assume (1)

https://github.com/observablehq/plot/blob/2ac08e266d1dd9743870d2c1ebbaf56ceb992524/src/transforms/group.js#L181

and if you want a reducer implementation, you would need another level of nesting to get (2):

```js
Plot.groupX({y: "count", fill: {reduce: {reduce: f}}}, {x: "species", fill: "island"})
```

but this should be considered a bug since we didn’t intend to change the interpretation. Hmm, tricky! I suppose we could look at the length of the reduce function to disambiguate but that could be brittle.

2023-03-20 18:09 UTC, mbostock commented
I wonder if we should make the map/reducer implementations much less ambiguous by using a symbol, e.g., {[Plot.reduce]: …} instead of {reduce: …} to declare an implementation. That would be possible like so:

```ts
export declare const reduce: unique symbol;

export interface ReducerImplementation {
  [reduce](index: number[], values: any[]): any;
}
```

It wouldn’t be backwards compatible, though… 🤔

2023-03-21 13:48 UTC, mbostock commented
Yes, please don’t make the label change in this documentation PR. It’s more subtle than it looks and is now delaying adding the documentation.

2023-03-21 18:01 UTC, mbostock requested changes
The changes to the Reducer types aren’t right.

A ReducerImplementation is an _implementation_; it can only be an object with a **reduce** method that takes _index_ and _values_ (plus a _context_ if there’s a **scope**, and an _extent_ in the case of the bin transform). A ReducerImplementation is never a named built-in reducer name, and a ReducerImplementation cannot declare a scale.

The only place where you can declare a scale override is in the context of a ChannelReducers object.

Also, the BinReducer types are specific to the bin transform, and therefore belong in src/transforms/bin; not sure why you moved them to src/reducer.

I think it’s okay to propose some small type changes along with documentation, but this is bigger than I was expecting. Changes to the types and lots of tests should be done separately from documentation. Also, I intentionally avoided documenting the reducer **scope** before because it’s _very_ rarely used and adds complexity. I’m not against including **scope** in the types if we can figure it out, but if we can’t, I definitely think we should cut it because we already have a huge amount of work just to do the documentation, and the types are useful as-is.

2023-03-21 18:29 UTC, Fil commented
Got it—I'm reverting all this. I was following my comment [above](https://github.com/observablehq/plot/pull/1360#issuecomment-1476386450), but it took me too far :)


Also this seems to work, but I wouldn't know how to express it as an _interface_:

```
export type ReducerImplementation =
  | {
      reduce(index: number[], values: any[]): any;
    }
  | {
      reduce(index: number[], values: any[], summary?: any): any;
      scope: "data" | "facet";
    };
```


```
export type BinReducerImplementation =
  | {
      reduce(index: number[], values: any[], extent: {x1: any; y1: any; x2: any; y2: any}): any;
    }
  | {
      reduce(index: number[], values: any[], summary?: any, extent?: {x1: any; y1: any; x2: any; y2: any}): any;
      scope: "data" | "facet";
    };

```

2023-03-24 16:59 UTC, Fil commented on src/transforms/bin.d.ts
> +   * distribution; if false or zero (the default), produce a probability
```suggestion
   * distribution; if false or zero (the default), produce a frequency
```

2023-03-25 03:33 UTC, mbostock approved these changes

2023-03-25 03:33 UTC, merged