fix #1453; axis label and href
observablehq/plot pull request #1455
Opened 2023-04-16 16:55 UTC by mbostock

Fixes #1453. The problem is that the **href** option was being passed to the axis label mark, too, which presumably caused the mark to be filtered out? I think we might need a more general solution for preventing channels on the singular axis label mark…

2023-04-16 17:31 UTC, Fil requested changes
I haven't given it much thought but I'm not sure how we could avoid having a list of option names we support for the label (whether that list is opt-in or like here, opt-out from all the options supported by the text mark).

After testing all the potentially-channel options (based on the typescript suggestions—thank you typescript!), these are the ones that also disappear the label: ariaLabel, fontSize, fillOpacity, opacity, rotate, title.

The mark crashes if passed a **filter** option.

2023-04-16 17:53 UTC, mbostock commented
This is still an improvement over the current behavior, so not sure it’s right to block this PR. I agree we should look for a more comprehensive fix however.

2023-04-16 20:13 UTC, mbostock commented
Rewritten to only allow constant options to propagate to the axis label.

2023-04-17 04:12 UTC, Fil approved these changes
thanks!

2023-04-17 05:29 UTC, merged