strokeWidth as a channel
observablehq/plot pull request #322
Opened 2021-04-13 12:00 UTC by Fil

closes #311

build : https://observablehq.com/@fil/plot-strokewidth-322

2021-05-06 12:40 UTC, Fil commented
Using this for a Sankey diagram, I'll need to set the width with a scale: identity. (Doesn't mean a scale isn't going to be useful in general.)

2021-07-30 07:40 UTC, ryoqun commented
@Fil @mbostock hi, is this going to be merged soon? :)

Also, I want tick's strokeWidth to be a channel as well.

2021-07-30 10:02 UTC, Fil commented
See #175 and #380

2021-07-31 15:08 UTC, mbostock requested changes
I support not having a scale for strokeWidth (at least for now), but it does feel arbitrary to only expose this property on the link mark. I would prefer to make this a standard channel on all marks, like we do with strokeOpacity. Even if that channel often goes unused, it’s still meaningful, and should be supported for consistency/symmetry. I might take a pass at this now.

2021-07-31 16:58 UTC, ryoqun commented
> I support not having a scale for strokeWidth (at least for now), but it does feel arbitrary to only expose this property on the link mark. I would prefer to make this a standard channel on all marks, like we do with strokeOpacity. Even if that channel often goes unused, it’s still meaningful, and should be supported for consistency/symmetry. I might take a pass at this now.

hey, I've always been fan of d3.js. thanks for moving this forward. :)

2021-08-08 16:16 UTC, mbostock commented on README.md
> -* **strokeWidth** - stroke width (in pixels)
This should be kept, right? The options that are supported as channels are also listed as constant options.

2021-08-09 11:17 UTC, ryoqun commented
hooray! thanks for working hard on this. so, strokeWidth for all marks? cool. :)

fyi, I'm creating a nice chart like this with plot (simply put, we're debugging any performance issues for distributed computing node's consensus formulation):

![image](https://user-images.githubusercontent.com/117807/128697829-3320446b-7146-4b40-b9af-eaf09c783be1.png)

And I want to use `strokeWidth` to embed extra scalar values into marks, instead of radius for visual conciseness and proper visual comparison (radius/area isn't cognitively easy than just width for visual measuring).

2021-08-09 11:25 UTC, Fil commented
wow! great example, I'd be curious to see it in action if you can share it! If you want to test this branch I've updated the build at https://observablehq.com/@fil/plot-strokewidth-322 (see also https://observablehq.com/@fil/plot-early-bird)

2021-08-09 12:31 UTC, ryoqun commented
>  I'd be curious to see it in action if you can share it!

yeah, I'd like to share but it's still in bad shape to share currently... needs some preparation to be published to the public..

> If you want to test this branch I've updated the build at https://observablehq.com/@fil/plot-strokewidth-322 (see also https://observablehq.com/@fil/plot-early-bird)

seems to work nicely! (I applied strokeWidth to Plot.dot and Plot.tickX. I can't wait official new version release with it. :)

![image](https://user-images.githubusercontent.com/117807/128706234-4d1f3460-df4d-4c8c-a3b1-79deeb7c49f9.png)

2021-08-10 13:21 UTC, mbostock approved these changes

2021-08-10 13:21 UTC, mbostock commented on README.md
>  * **strokeOpacity** - a stroke opacity; bound to the *opacity* scale
Add strokeWidth here?

2021-08-10 16:54 UTC, merged

2021-08-20 11:51 UTC, Fil commented
example for CHANGELOG:
![strokeWidth-channel](https://user-images.githubusercontent.com/7001/130228992-eb2452f1-8822-4239-87b7-07f79e5a2ccb.png)

Plot.dotX(d3.range(41), { strokeWidth: (d) => (1 + d) / 15 }).plot()

2021-11-10 15:09 UTC, enjalot commented
> Can do, but I'm not sure it's worth it. Links tend to come with value=1…10 (co-occurences as in the miserables.json example), or 0…1, or sometimes from distance matrices 0…infty, and I feel it's always more "graphic tweaking" than really using it as an encoding to be shared with another mark.

I didn't think about the "shared with another mark" aspect, but from the perspective of "Plot figures out how to map data space to graphic space for me and I just want to tweak the pixels" having a scale here is what I expect. It's similar to how I would think about the `r` channel in dots, where I usually want to impose some maximum size. That could be considered a graphic tweak but it's a pretty meaningful one.
I suppose for the same reason I also want a scale for fontSize, because without a scale I have to go outside of Plot to calculate the extent of the data and do the math that Plot would do for me in the other channels, like opacity