Add shape-rendering to mark style
observablehq/plot pull request #419
Opened 2021-05-28 13:52 UTC by martgnz

This PR adds the [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) attribute to the list of mark styles.

2021-05-28 16:17 UTC, Fil commented
Thanks! Have you by any chance looked at the examples in the test/plots/ directory and seen a plot that would benefit from using the option?

2021-05-30 09:54 UTC, martgnz commented
I didn't see any test plot that could benefit so I added a new snapshot test (which could be a useful example when https://github.com/observablehq/plot/pull/415 lands too).

There's also two new small unit tests.

2021-05-30 10:23 UTC, Fil requested changes
great example, thanks!

2021-05-30 10:23 UTC, Fil commented on test/plots/us-presidential-forecast-2016.js
> +      labelAnchor: 'left',
```suggestion
      label: "Electoral votes for Hillary Clinton →",
      labelAnchor: "left",
```

consistent style for quotes

2021-05-30 10:23 UTC, Fil commented on test/plots/us-presidential-forecast-2016.js
> +      Plot.barY(data, {x: "dem_ev", y: "prob", shapeRendering: 'crispEdges', fill:'dem_ev', stroke:'dem_ev' }),
```suggestion
      Plot.barY(data, {x: "dem_ev", y: "prob", shapeRendering: "crispEdges", fill: "dem_ev", stroke: "dem_ev" }),
```

2021-05-30 10:24 UTC, Fil approved these changes
we'll be waiting on #415 then

2021-07-20 14:36 UTC, Fil commented
I've added a build in https://observablehq.com/@fil/quantile-threshold-shaperendering-415-419

2021-07-20 21:12 UTC, mbostock requested changes

2021-07-20 21:12 UTC, mbostock commented on src/style.js
> +  mark.shapeRendering = string(shapeRendering);
```suggestion
  mark.shapeRendering = impliedString(shapeRendering, "auto");
```

2021-08-01 03:18 UTC, mbostock commented on test/plots/us-presidential-forecast-2016.js
> +      Plot.barY(data, {x: "dem_ev", y: "prob", shapeRendering: "crispEdges", fill: "dem_ev", stroke: "dem_ev" }),
We don’t want a bar here because the _x_-scale is quantitative (number of electoral votes), not ordinal. I’ll rewrite this example.

2021-08-01 03:24 UTC, merged